apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moscow-upf-pvc
  namespace: telecom
  labels:
    app: moscow-upf
    component: 5g_upf
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi
